export const visualAssets = [
  {
    id: "asset-01189",
    title: "Citrus panorama",
    collection: "Agriculture and Soil",
    path: "/images/visuals/home/citrus-pano-hero.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/originals/agriculture-soil/agriculture-soil_2018-01-26_citrus-pano-jw6ch7nmo_0001.jpg",
    alt: "Panoramic citrus orchard rows across working farmland",
    placement: "Homepage hero",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01189-mobile",
    title: "Citrus panorama mobile crop",
    collection: "Agriculture and Soil",
    path: "/images/visuals/home/citrus-pano-mobile.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/originals/agriculture-soil/agriculture-soil_2018-01-26_citrus-pano-jw6ch7nmo_0001.jpg",
    alt: "Citrus orchard rows cropped for mobile display",
    placement: "Homepage mobile hero",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01197",
    title: "Aerial field",
    collection: "Landscapes and Wildflowers",
    path: "/images/visuals/home/aerial-field.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/landscapes-wildflowers/landscapes-wildflowers_2017-04-21_aerial-jw6ch7nmo_0004.jpg",
    alt: "Aerial view of working agricultural land",
    placement: "Homepage field proof reel",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00993",
    title: "Lemons wide",
    collection: "Agriculture and Soil",
    path: "/images/visuals/home/lemons-wide.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/agriculture-soil/agriculture-soil_2019-03-13_lemons-dgpe3ee3q_0014.jpg",
    alt: "Lemons growing in orchard rows",
    placement: "Soil Intelligence and Learn",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00992",
    title: "Lemons detail",
    collection: "Agriculture and Soil",
    path: "/images/visuals/home/lemons-detail.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/agriculture-soil/agriculture-soil_2019-03-13_lemons-dgpe3ee3q_0013.jpg",
    alt: "Close view of citrus fruit and leaves",
    placement: "Soil Intelligence mosaic",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00982",
    title: "Lemons portrait",
    collection: "Agriculture and Soil",
    path: "/images/visuals/home/lemons-portrait.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/agriculture-soil/agriculture-soil_2019-03-13_lemons-dgpe3ee3q_0003.jpg",
    alt: "Portrait crop of lemons growing on a tree",
    placement: "Soil Intelligence mosaic",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00345",
    title: "Slough restoration",
    collection: "Ecosystems and Restoration",
    path: "/images/visuals/home/slough-restoration.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/ecosystems-restoration/ecosystems-restoration_2020-10-13_slough-lookout-f4haq_0008.jpg",
    alt: "Restored wetland and living landscape viewed from above",
    placement: "Restoration contrast and visual proof",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01179",
    title: "Cachuma drought",
    collection: "Drought and Water Supply",
    path: "/images/visuals/home/drought-lake.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/drought-water-supply/drought-water-supply_2019-08-28_cachuma-jw6ch7nmo_0005.jpg",
    alt: "Low reservoir water level under drought pressure",
    placement: "The Other Half contrast and Support urgency",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01424",
    title: "Water conservation",
    collection: "Drought and Water Supply",
    path: "/images/visuals/home/water-conservation.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/drought-water-supply/drought-water-supply_undated_water-conservation_0010.jpg",
    alt: "Water conservation landscape under dry conditions",
    placement: "Water resilience proof",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01153",
    title: "Citrus pump station",
    collection: "Water Infrastructure",
    path: "/images/visuals/edison/citrus-pump-station.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/water-infrastructure/water-infrastructure_2023-05-13_citrus-pump-station-jw6ch7nmo_0012.jpg",
    alt: "Citrus farm pump station and irrigation infrastructure",
    placement: "Edison hero",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01547",
    title: "Aqueduct subsidence",
    collection: "Water Infrastructure",
    path: "/images/visuals/edison/aqueduct-subsidence.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/water-infrastructure/water-infrastructure_2022-03-23_aqueduct-subsidence_0022.jpg",
    alt: "Aqueduct infrastructure affected by subsidence",
    placement: "Edison and Evidence water infrastructure proof",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01141",
    title: "Lake level",
    collection: "Drought and Water Supply",
    path: "/images/visuals/edison/lake-level.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/drought-water-supply/drought-water-supply_2021-10-28_lake-ai-level-jw6ch7nmo_0008.jpg",
    alt: "Low lake level showing drought stress",
    placement: "Edison and Evidence drought proof",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01188",
    title: "Citrus research",
    collection: "Agriculture and Soil",
    path: "/images/visuals/edison/citrus-research.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/agriculture-soil/agriculture-soil_2018-01-26_citrus-jw6ch7nmo_0005.jpg",
    alt: "Citrus orchard used as field research context",
    placement: "Edison research agenda",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00146",
    title: "Current USDM",
    collection: "Reference Assets",
    path: "/images/visuals/edison/current-usdm.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/reference-assets/reference-assets_undated_current-usdm_0001.jpg",
    alt: "United States drought monitor map",
    placement: "Evidence reference visual",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00856",
    title: "Delta restoration",
    collection: "Ecosystems and Restoration",
    path: "/images/visuals/evidence/delta-restoration.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/ecosystems-restoration/ecosystems-restoration_2019-02-22_delta_0002.jpg",
    alt: "Delta landscape showing water and restored habitat",
    placement: "Evidence and living systems",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01315",
    title: "Thompson meadow drone",
    collection: "Ecosystems and Restoration",
    path: "/images/visuals/why/meadow-drone.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/ecosystems-restoration/ecosystems-restoration_2025-07-08_an-thompson-meadow-drone_0025.jpg",
    alt: "Drone view of restored meadow and water-shaped landscape",
    placement: "The Other Half living systems",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00191",
    title: "State Fair action",
    collection: "People, Programs, Community",
    path: "/images/visuals/adopt/state-fair-action.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/people-programs-community/people-programs-community_2018-07-24_state-fair_0005.jpg",
    alt: "Community members gathered around a public program table",
    placement: "Adopt-A-Meter public participation",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01403",
    title: "SOW Sarakki",
    collection: "People, Programs, Community",
    path: "/images/visuals/adopt/sow-sarakki.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/people-programs-community/people-programs-community_undated_sow-sarakki_0001.jpg",
    alt: "Community program participant connected to soil and land work",
    placement: "Adopt-A-Meter community strip",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01402",
    title: "SOW Rodriguez",
    collection: "People, Programs, Community",
    path: "/images/visuals/adopt/sow-rodriguez.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/people-programs-community/people-programs-community_undated_sow-rodriguez_0003.jpg",
    alt: "Person photographed for a soil and community program",
    placement: "Adopt-A-Meter community strip",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01395",
    title: "SOW Coolidge",
    collection: "People, Programs, Community",
    path: "/images/visuals/adopt/sow-coolidge.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/people-programs-community/people-programs-community_undated_sow-coolidge_0002.jpg",
    alt: "Person photographed for a soil and community program",
    placement: "Adopt-A-Meter community strip",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01392",
    title: "Relationship field",
    collection: "People, Programs, Community",
    path: "/images/visuals/about/relationship-field.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/people-programs-community/people-programs-community_undated_sow-ardill_0007.jpg",
    alt: "Community and field relationship connected to soil work",
    placement: "About relationship history",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00189",
    title: "State Fair community",
    collection: "People, Programs, Community",
    path: "/images/visuals/adopt/state-fair-community.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/people-programs-community/people-programs-community_2018-07-24_state-fair_0003.jpg",
    alt: "Community members gathered around a public program table",
    placement: "Adopt-A-Meter and Projects",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01152",
    title: "Citrus pump station alternate",
    collection: "Water Infrastructure",
    path: "/images/visuals/edison/citrus-pump-alt.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/water-infrastructure/water-infrastructure_2023-05-13_citrus-pump-station-jw6ch7nmo_0011.jpg",
    alt: "Irrigation infrastructure on a citrus farm",
    placement: "Edison economics and support visuals",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01178",
    title: "Cachuma drought alternate",
    collection: "Drought and Water Supply",
    path: "/images/visuals/evidence/cachuma-drought.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/drought-water-supply/drought-water-supply_2019-08-28_cachuma-jw6ch7nmo_0004.jpg",
    alt: "Low reservoir water level under drought pressure",
    placement: "Evidence food and climate bridge",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00344",
    title: "Slough living system",
    collection: "Ecosystems and Restoration",
    path: "/images/visuals/evidence/slough-living-system.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/ecosystems-restoration/ecosystems-restoration_2020-10-13_slough-lookout-f4haq_0007.jpg",
    alt: "Restored wetland and living landscape",
    placement: "Evidence and Edison biodiversity",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00991",
    title: "Soil citrus",
    collection: "Agriculture and Soil",
    path: "/images/visuals/learn/soil-citrus.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/agriculture-soil/agriculture-soil_2019-03-13_lemons-dgpe3ee3q_0012.jpg",
    alt: "Citrus fruit and leaves in an orchard",
    placement: "Learn, Evidence, Projects, and Edison",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01537",
    title: "Water proof",
    collection: "Water Infrastructure",
    path: "/images/visuals/learn/water-proof.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/water-infrastructure/water-infrastructure_2022-03-23_aqueduct-subsidence_0012.jpg",
    alt: "Aqueduct infrastructure under water pressure",
    placement: "Learn module",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01145",
    title: "Edison water",
    collection: "Water Infrastructure",
    path: "/images/visuals/projects/edison-water.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/water-infrastructure/water-infrastructure_2023-05-13_citrus-pump-station-jw6ch7nmo_0004.jpg",
    alt: "Citrus farm irrigation infrastructure",
    placement: "Projects Edison feature",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00341",
    title: "Soil climate landscape",
    collection: "Ecosystems and Restoration",
    path: "/images/visuals/projects/soil-climate.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/ecosystems-restoration/ecosystems-restoration_2020-10-13_slough-lookout-f4haq_0004.jpg",
    alt: "Restored wetland and living landscape",
    placement: "Projects and About",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01627",
    title: "Field support",
    collection: "Brand Photography",
    path: "/images/visuals/support/field-support.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/brand-photography/brand-photography_undated_dan-gold-h0jp8px-0zw_0001.jpg",
    alt: "Hands holding living soil and plants",
    placement: "Support visual band and decision guide",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-01176",
    title: "Drought contrast",
    collection: "Drought and Water Supply",
    path: "/images/visuals/why/drought-contrast.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/drought-water-supply/drought-water-supply_2019-08-28_cachuma-jw6ch7nmo_0002.jpg",
    alt: "Low reservoir water level showing drought pressure",
    placement: "The Other Half visual contrast",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
  {
    id: "asset-00343",
    title: "Restoration contrast",
    collection: "Ecosystems and Restoration",
    path: "/images/visuals/why/restoration-contrast.webp",
    sourcePath:
      "NEW VISUALS/photo-bank/web/assets/previews/ecosystems-restoration/ecosystems-restoration_2020-10-13_slough-lookout-f4haq_0006.jpg",
    alt: "Restored living landscape with water and vegetation",
    placement: "The Other Half visual contrast and Edison practice stack",
    credit: "TCU Media Library",
    license: "Source/license pending verification in media bank metadata",
  },
];

export const visualById = visualAssets.reduce((lookup, asset) => {
  lookup[asset.id] = asset;
  return lookup;
}, {});
